accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^post/$', views.userPost, name="userPost"),
    url(r'^pref/$', views.selectPref, name="selectPref"),
]

pinclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', views.homepage),
    url(r'^about/$', views.about),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User



class Preference(models.Model):
	name = models.CharField(max_length = 50)

	def __str__(self):
		return self.name


class Image(models.Model):
	photo = models.ImageField(null=True,blank=True,upload_to='media/')
	tag = models.ForeignKey(Preference,on_delete = models.CASCADE)

	def __str__(self):
		return self.photo.name[6:]


class UserProfile(models.Model):
	user = models.OneToOneField(User,on_delete = models.CASCADE)
	choices = models.ManyToManyField(Preference)

	def __str__(self):
		return self.user.username

accounts/forms.py
from django import forms
from . import models

class SelectPreferences(forms.ModelForm):
    class Meta:
        model = models.UserProfile
        fields = ['user', 'choices']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from . models import Image, UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request, user)
            return redirect('/accounts/pref')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/accounts/post')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/about')

def userPost(request):
    userprofile = UserProfile.objects.get(user=request.user)
    images = []
    for img in Image.objects.all():
        if img.tag in userprofile.choices.all():
            images.append(img)
    return render(request, 'accounts/wall.html', {'userprofile':userprofile, 'images':images})

@login_required(login_url = '/accounts/login/')
def selectPref(request):
    if request.method == 'POST':
        form = forms.SelectPreferences(request.POST, request.FILES)
        if form.is_valid():
            #save preferences
            instance = form.save()
            instance.save()
            return redirect('/accounts/post')
    else:
        form = forms.SelectPreferences()
    return render(request, 'accounts/select_preferences.html', {'form': form})

pinclone/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html'%}


{% block content%}
  <h1>Log in</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next}}">
    {% endif %}
    <input type="submit" value="Login">
  </form>

{% endblock %}

accounts/templates/accounts/select_preferences.html
{% extends 'base_layout.html' %}


{% block content %}
  <div class="select-preferences">
    <h2>Select your preferences</h2>
    <form class="site-form" action="{% url 'accounts:selectPref' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form}}
      <input type="submit" value="Create">
    </form>
  </div>


{% endblock%}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}


{% block content%}
  <h1>Signup</h1>
  <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
  </form>

{% endblock %}

accounts/templates/accounts/wall.html
{% extends 'base_layout.html'%}

{% block content%}
  <h1>{{ userprofile.user.username }}</h1>
  {% for img in images %}
    <img src="{{ img.photo.url }}" >
  {% endfor %}
{% endblock%}

templates/about.html
{% extends 'base_layout.html'%}

{% block content%}
  <h1>About</h1>
{% endblock%}

templates/base_layout.html
{% load staticfiles %}


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Pin Clone</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  </head>
  <body>
      <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Pin Clone</a>
                <!-- image -->
            </div>
            <div class="collapse navbar-collapse" id="menu">

                  {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
                  <li><a href="#">Home<span class="glyphicon glyphicon-user color-blue"></span></a> </li>
                  <li><a href="#">Profile</a> </li>
                  <li><a href="#">Notifications</a> </li>
                </ul>

                  <form class="navbar-form navbar-left" action="/action_page.php">
				  <div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				  </div>
				  <button type="submit" class="btn btn-default">Submit</button>
                  </form>

                  <div class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true"><span style="font-size: 23px" class="glyphicon glyphicon-option-horizontal"></span></a>
							<ul class="dropdown-menu">
								<li><a href="#">Edit Profile</a> </li>
								<li><a href="#">Settings</a> </li>
                                   <li role="separator" class="divider"></li>
								<li>
                                <a>
                                  <form class="logout-link" action="{% url 'accounts:logout'%}" method="post">
                                    {% csrf_token %}
                                     <button type="submit" class="btn navbar-btn">Logout</button>
                                  </form>
                                </a>
                                </li>
							</ul>
					</li>
				</div>


                  {% else %}
                  <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:login'%}">Login</a></li>
                    <li><a href="{% url 'accounts:signup'%}">Signup</a></li>
                    </ul>
                  {% endif %}

            </div>
        </div>

      </nav>

    <div class="wrapper">
      {% block content%}
      {% endblock %}
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  </body>
</html>

templates/homepage.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Pin Clone</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  </head>
  <body>



    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  </body>
</html>